services:
  - type: web
    name: worldcup-predictor-api
    env: node
    region: oregon
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        value: mongodb+srv://learnMDB:<db_password>@cluster0.6igo8nz.mongodb.net/?appName=Cluster0
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://your-vercel-app.vercel.app
